In [38]:
import numpy as np
#sabit tipte veri saklar, hızlı ve fonksiyoneldir. yüksek seviyeden işlemler yapar

In [26]:
a = [1,13,22,4]
b = [2,34,6,33]

In [27]:
ab = []
#a ve listesindeki elemanların çarpımını ab listesine ekle işlemi, klasik python
for i in range(0, len(a)):
    ab.append(a[i] * b[i])

In [28]:
ab

[2, 442, 132, 132]

In [29]:
#yukarıda ki işlemi numpy ile yapalım
a = np.array([1,13,22,4]) #a listesini numpy arrayine çevirdik
b = np.array([2,34,6,33])
a*b # direk işlem yapma kolaylığı 

array([  2, 442, 132, 132])

In [30]:
#numpy array i oluşturmak (creating numpy arrays)
a = np.array([1,2,3,4,5]) #liste üzerinden numpy arrayi oluşturuldu
a

array([1, 2, 3, 4, 5])

In [31]:
type(a)

numpy.ndarray

In [32]:
#girilen sayı kadar sıfır değeri oluşturur
np.zeros(7, dtype= int)

array([0, 0, 0, 0, 0, 0, 0])

In [33]:
np.random.randint(13,113, size= 9) #13 min 113 max sınır, size adeti verir

array([ 75,  90, 100,  65,  42,  13, 104,  18,  56])

In [34]:
#belirli bir istatistiksel dağılıma göre sayı üretme 
#Üç argümanı vardır.1-Oluşturulmak istenen normal dağılımlı kitlenin ortalaması, 
#2-argüman, 3- boyut bilgisi girilir yani (ortalama, standart sapma, (x,y array))
np.random.normal(13,5,(2,5))

array([[ 2.76788403, 18.42023473, 15.98805199, 16.82586387, 18.12497878],
       [14.48188287, 12.48132432, 15.93731312, 25.0139653 , 16.76380643]])

In [35]:
"""numpy array özellikleri
ndim: boyut sayısı
shape: boyut bilgisi
size: toplam eleman sayısı
dtype: array veri tipi
"""

'numpy array özellikleri\nndim: boyut sayısı\nshape: boyut bilgisi\nsize: toplam eleman sayısı\ndtype: array veri tipi\n'

In [36]:
#yeniden şekillendirme(reshaping)
a= np.random.randint(1,13,size=12)
a #tek boyut

array([ 5, 10,  3,  4,  4,  7,  2,  8,  7,  1,  3, 11])

In [37]:
a.reshape(3,4) #çift boyutt

array([[ 5, 10,  3,  4],
       [ 4,  7,  2,  8],
       [ 7,  1,  3, 11]])

In [44]:
#index işlemleri
m = np.random.randint(25,size=(3,5))
m

array([[10,  2,  7,  8,  9],
       [ 1, 19, 11,  5, 15],
       [ 8, 23,  1, 24, 21]])

In [45]:
m[2,3] #virglden öncesi satır sonrası sütunları temsil eder

24

In [46]:
m[2,3] = 900 #atama
m

array([[ 10,   2,   7,   8,   9],
       [  1,  19,  11,   5,  15],
       [  8,  23,   1, 900,  21]])

In [47]:
m[2,3] = 13.13 #numpy arrayi sabit tiptir, float değer yazınca kendi tip bilgisi olan inte çevirir değeri öyle yazar
m

array([[10,  2,  7,  8,  9],
       [ 1, 19, 11,  5, 15],
       [ 8, 23,  1, 13, 21]])

In [50]:
m[0:2 , 1:3]

array([[ 2,  7],
       [19, 11]])

In [51]:
f = np.arange(13,100,10)
f# 13 den başla 100 e kadar git 10ar 10ar arttır

array([13, 23, 33, 43, 53, 63, 73, 83, 93])

In [55]:
#fancy index 
catch = [1,5,7,8] 
f[catch] #index bigilerini teker teker yazma zahmetinden kurtarır

array([23, 63, 83, 93])

In [56]:
f[f<50] #koşullu seçme işlemi

array([13, 23, 33, 43])

In [57]:
f/5

array([ 2.6,  4.6,  6.6,  8.6, 10.6, 12.6, 14.6, 16.6, 18.6])

In [59]:
f = np.subtract(f,3) #çıkarma işlemi
"""
add ekleme işlemi
mean ortalama işlemi
sum toplama işlemi
min işlemi
max işlemi
var varyans işlemi
"""

'\nadd ekleme işlemi\nmean ortalama işlemi\nsum toplama işlemi\nmin işlemi\nmax işlemi\nvar varyans işlemi\n'

In [60]:
f

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [62]:
#iki bilinmeyenli denklem çözümü
#5*x0 + x1 = 12
#x0 + 3*x1 = 10 ör
a = np.array([[5,1] , [1,3]]) #xo katsaıları, x1 katsayıları
b = np.array([12,10]) #sonuçlar
np.linalg.solve(a,b) #hesaplama

array([1.85714286, 2.71428571])